### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by luckyrobot**
Required for https://github.com/porter-finance/handbook/issues/8

### CODE REVIEW

**Review by jordanalexandermeyer — COMMENTED** [review]
I'm not familiar with using licenses, so I'll defer to others.

**Review by RusseII — COMMENTED** [review]
Why did you pick this type of license? 

I see maple uses a different one https://github.com/maple-labs/maple-core/blob/main/LICENSE

https://github.com/gnosis/safe-contracts/blob/main/LICENSE gnosis uses different one as well 

https://github.com/Uniswap/v3-core/blob/main/LICENSE uniswap different as well

**Comment by RusseII** [comment]
>updated to gnu 3.0

Why that license? IDK too much about any of them - I doubt it matters much for handbook repo tho ...

**Comment by chand1012** [comment]
> I doubt it matters much for a handbook repo tho ...

Yeah it really doesn't. GPLv3 will be fine for this.

**Review by RusseII — APPROVED** [review]

**Pull request merged**
