### PR TITLE
Create communication.md

### PR DESCRIPTION
**Pull request by Geczy**
# The problem

[Context started here](https://discord.com/channels/903094151002857492/927340122435895296/927963349008912424)

Google drive doesn't have a good interface to promote efficiency

I often find myself frustrated at having too many email notifications to keep track of activity, or a long list of activities in the drive web interface that has no relevance to me (currently everything is relevant but later on this may not be the case). 

I also have no good page to view all the files in one view. I have to drill down each folder to explore what exists at the company. There is no "preview" or description of what each folder means

# Proposed solution

I recommended [Coda.io](https://coda.io/). A lot of other companies seem to be using it, like robinhood, square, uber, intercom

Anyone can edit / view / comment with a google account, just like google docs, on both coda and notion

The navigation issue is solved, [view example here](https://coda.io/@justin/endless-idea-generator)

Each parent item can be its own page with an introduction / more info rather than an empty folder that contains more folders

# Going forward

Automatic google doc [import](https://help.coda.io/en/articles/3544385-how-can-i-import-google-docs-into-coda#:~:text=Importing%20Google%20Docs%20into%20Coda&text=Under%20the%20%22Import%22%20header%20select%20Google%20Docs&text=Search%20for%20and%20select%20the,Click%20'Import')

# Alternatives

I tried looking for google chrome extensions that make google drive better, but [none exist](https://chrome.google.com/webstore/search/google%20drive?hl=en&_category=extensions)

Notion.so is also a good alternative, I haven't found any issues using it yet. Coda seems to be used more widely by businesses

[Noton vs coda](https://coda.io/@john/coda-notion)

[Information hierarchy, notion vs coda](https://coda.io/@john/coda-notion/information-hierarchy-13)

[Reddit discusses notion vs coda](https://www.reddit.com/r/Notion/comments/ohtxl7/notion_vs_coda_2021/)

### CODE REVIEW

**Comment by RusseII** [comment]
Can we dodge this issue by reducing our usage of drive and focusing on handbook first approach/gh for discussion? 
 
Gitlabs advice: 
https://about.gitlab.com/handbook/tools-and-tips/#first-an-important-message---dont-use-google-driveapps-unless-you-have-to

There was also an issue with a similar nit - https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/5143

**Comment by Geczy** [comment]
I dont think so. Github doesn't have support for features like advanced tables, live collaboration, eg when discussing or taking notes during a meeting, among many other missing features we would use Coda / Notion for. A few others are live voting like in a poll, sharing out docs to get comments (they would need to fork and create a pr then add comments?). Just seems very slow

Let me know if I'm missing something here

**Comment by RusseII** [comment]
> live collaboration, eg when discussing or taking notes during a meeting 

That's true. I will follow up with thoughts about this. 

>sharing out docs to get comments (they would need to fork and create a pr then add comments?)

What would be an example here? Following Gitlabs model - I believe it'd be a PR with the document then teammates leave comments on that PR. So I should have made https://docs.google.com/document/d/1684GUBC8tgfFVr-lC5m7VSkyFwqpXIyijO71BD-9IWg/edit as a PR then shared that vs using google docs.

**Comment by Geczy** [comment]
> What would be an example here? Following Gitlab's model - I believe it'd be a PR with the document then teammates leave comments on that PR. So I should have made https://docs.google.com/document/d/1684GUBC8tgfFVr-lC5m7VSkyFwqpXIyijO71BD-9IWg/edit as a PR then shared that instead of using google docs.

an example would be like merging this PR before sending it out to others for comments (it can happen)

or sending any of the other md's that are already in here out to others for commenting. they would each need to fork and pr and add comments, a long process over just a live doc w/ comment system

**Comment by jordanalexandermeyer** [comment]
I'd rather not have to onboard everyone to a new software. Although there is some friction, I think Google Drive gets us 80% of the way there.

**Comment by RusseII** [comment]
So, just to clarify and summarize here - the main issues are:
1. Notification fragmentation across platforms (github, drive, discord) 
2. It's not clear when to look at google drive or what to look at

Is that correct? 

I have concerns that using another software would perpetuate this issue further (since we'd still be using gcalendar, gmeet, etc...) and notion/coda take the handbook approach which we are already doing with git..

Thoughts on updating this proposal and MR to add the information from https://about.gitlab.com/handbook/tools-and-tips/#first-an-important-message---dont-use-google-driveapps-unless-you-have-to ? 

Then we have the expectation that team members check github notifications and stay on top of those - but disable/do not check drive notifications unless they are explicitly shared on discord/referenced via github. 

@Geczy

**Comment by Geczy** [comment]
after looking at gitbook docs, im 100% ok with no introducing a new tool. @RusseII can we get gitbooks scheduled for to be added for us?

although i do have to mention that sometimes there's a tool better suited for a task, so its not always in our best interest to ignore them to -1 our toolstack :)

**Pull request closed without merging**
