### PR TITLE
Add workflow proposal - Flights 

### PR DESCRIPTION
**Pull request by RusseII**
Preread: https://about.gitlab.com/handbook/communication/#everything-starts-with-a-merge-request

I think traditional agile is too heavyweight for our team structure and goals. I propose following the model of [Flights](https://simonhoiberg.medium.com/the-flight-manual-9e1aedd04fbf).

For example - our current [story board](https://github.com/orgs/porter-finance/projects/4) would be our first flight - with @jordanalexandermeyer as the pilot and with an ETA landing date. 

Then after completing the onboarding we would likely have two flights in parallel - one around first iteration of smart contracts piloted by @Geczy and another one around the frontend/design work.

Please share thoughts & feedback.

### CODE REVIEW

**Comment by jordanalexandermeyer** [comment]
I really like this idea.

I think it adds flexibility to our workflow.

- I'd still like to do daily standups
- I also think we should have flight plannings. The current flight did not need planning but future ones will.
- I'm not sure if we need flight retros. I did not find them particularly useful at Zillow. We can give feedback as the flight is going on. But I'm open to doing them.

It's also low stakes to try it. We can always move to Agile if it's not working.

**Review by jordanalexandermeyer — APPROVED** [review]

**Comment by Namaskar-1F64F** [comment]
I am game to try. Want me to add some context into the guidebook or are we ok with the link?

**Comment by RusseII** [comment]
>I think we should have flight plannings. The current flight did not need planning but future ones will.
I agree - but I don't think it should be like traditional planning with sync meeting and estimations

>I am game to try. Want me to add some context into the guidebook or are we ok with the link?
Up to you - my thoughts was to leave link until we solidify it more as our process, then add more details.

**Comment by Geczy** [comment]
Could you provide a better link on flights, one that outlines a typical structure and example dev scenario?

**Review by Namaskar-1F64F — APPROVED** [review]

**Comment by RusseII** [comment]
> Could you provide a better link on flights, one that outlines a typical structure and example dev scenario?

Will follow up on this. Thanks for the feedback team!

**Pull request merged**
